name = "BayesianIntegral"
uuid = "170c7662-660e-5658-93f2-9369b3e86d75"
version = "0.2.0"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Distributions = "^0.25.115"
LinearAlgebra = "^1.12.0"
Optim = "^1.10.0"
Random = "^1.11.0"
Test = "^1.11.0"
julia = "^1.0"
